spring:
  datasource:
    #mysql
    driverClassName: com.mysql.jdbc.Driver
    name: mysql
    url: jdbc:mysql://localhost:3306/alex
    username: root
    password: a123456
    validationQuery: SELECT 1
  cloud:
    config:
      label: master
      server:
        jdbc:
          sql: select `key`,`value` from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
  profiles:
    active: jdbc
server:
  port: 8888